spring:
  application:
    name:
      student-management-system

  datasource:
    url: jdbc:postgresql://localhost:5432/student_db
    username: postgres
    password: admin
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect

logging:
  level:
    com.example.student_management_system: DEBUG
    org.springframework.security: TRACE



#    spring:
#      datasource:
#      url: jdbc:postgresql://localhost:5432/test
#      username: postgres
#      password: password
#      driver-class-name: org.postgresql.Driver
#
#      jpa:
#      database-platform: org.hibernate.dialect.PostgreSQLDialect
#      hibernate:
#      ddl-auto: update
#      show-sql: true
#      open-in-view: true
#      properties:
#      org:
#      hibernate:
#      envers:
#      audit_table_suffix: _AUDIT